using Project_Euler_Interface.Problems;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading;
using System.Windows.Forms;

namespace Project_Euler_Interface
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void button3_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void button2_Click(object sender, EventArgs e)
        {
            //copy answer to clipboard
            Clipboard.SetText(textBox1.Text);
        }

        private void button1_Click(object sender, EventArgs e)
        {
            //copy code to clipboard
            Clipboard.SetText(richTextBox2.Text);
        }

        private void comboBox1_SelectedIndexChanged(object sender, EventArgs e)
        {
            switch (comboBox1.SelectedIndex)
            {
                case 0:
                    richTextBox1.Text = "If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23." + "\n" + "\n" +

                                        "Find the sum of all the multiples of 3 or 5 below 1000.";
                    textBox1.Text = P1.ProblemOne().ToString();
                    //richTextBox2.Text = ReadAllText(P1.cs);
                    break;

                case 1:
                    richTextBox1.Text = "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:" + "\n" +

                                        "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ..." + "\n" + "\n" +

                                        "By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.";
                    textBox1.Text = P2.FibonacciSum().ToString();
                    break;

                case 2:
                    richTextBox1.Text = "The prime factors of 13195 are 5, 7, 13 and 29." + "\n" + "\n" +

                                        "What is the largest prime factor of the number 600851475143 ? ";
                    textBox1.Text = P3.LargestPrime();
                    break;

                case 3:
                    richTextBox1.Text = "A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99." + "\n" + "\n" +

                                        "Find the largest palindrome made from the product of two 3 - digit numbers.";
                    textBox1.Text = P4.largestPalindrome();
                    break;

                case 4:
                    richTextBox1.Text = "2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder." + "\n" + "\n" +

                                        "What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20 ? ";
                    textBox1.Text = P5.SmallestMultiple();
                    break;

                case 5:
                    richTextBox1.Text = "The sum of the squares of the first ten natural numbers is, " + "\n" + "\n" +

                                        "12 + 22 + ... + 102 = 385" + "\n" + 
                                        "The square of the sum of the first ten natural numbers is," + "\n" + "\n" + 

                                        "(1 + 2 + ... + 10)2 = 552 = 3025" + "\n" +
                                        "Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640." + "\n" + "\n" +

                                        "Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.";
                    textBox1.Text = P6.SquareSum();
                    break;

                case 6:
                    richTextBox1.Text = "By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13." + "\n" + "\n" +

                                        "What is the 10 001st prime number ? ";
                    textBox1.Text = P7.FindPrimeNumber();
                    break;

            }
        }
    }
}
